name=MemoryInfo
version=1.1.0
author=Olivier FOURNET
maintainer=Olivier FOURNET <olivier.fournet@free.fr>
sentence=MemoryInfo pour les ESP8266, ESP32, AVR, ...
paragraph=MemoryInfo Une bibliothèque Arduino légère et efficace pour surveiller l'utilisation de la mémoire heap sur les microcontrôleurs ESP8266, ESP32 et AVR.
category=Memory
url=https://github.com/Fo170/MemoryInfo
architectures=esp32,esp8266,avr
includes=MemoryInfo.h
license=GPL-3.0-only